/*******************************************************************************/
/*  This file is auto-generated by GUIX Studio. Do not edit this file by hand. */
/*  Modifications to this file should only be made by running the GUIX Studio  */
/*  application and re-generating the application. For more information please */
/*  refer to the GUIX Studio user's guide, or visit our web site at            */
/*  www.expresslogic.com.                                                      */
/*                                                                             */
/*  GUIX Studio Revision 5.3.2.2                                               */
/*  Date (dd.mm.yyyy): 17. 4.2017   Time (hh:mm): 17:56                        */
/*******************************************************************************/


#define GUIX_STUDIO_GENERATED_FILE
#include <stddef.h>
#include "SmartWine_resources.h"
#include "SmartWine_specifications.h"

WARNING_WINDOW_CONTROL_BLOCK warning_window;
SPLASH_CONTROL_BLOCK splash;
ALERT_WINDOW_CONTROL_BLOCK alert_window;
AMS_WINDOW_CONTROL_BLOCK ams_window;
S7_WINDOW_CONTROL_BLOCK s7_window;
MAIN_WINDOW_CONTROL_BLOCK main_window;

UINT gx_studio_text_button_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_TEXT_BUTTON *button = (GX_TEXT_BUTTON *) control_block;
    GX_TEXT_BUTTON_PROPERTIES *props = (GX_TEXT_BUTTON_PROPERTIES *) info->properties;
    status = gx_text_button_create(button, info->widget_name, parent, props->string_id, info->style, info->widget_id, &info->size);
    if (status == GX_SUCCESS)
    {
        gx_text_button_font_set(button, props->font_id);
        gx_text_button_text_color_set(button, props->normal_text_color_id, props->selected_text_color_id);
    }
    return status;
}

UINT gx_studio_checkbox_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_CHECKBOX *button = (GX_CHECKBOX *) control_block;
    GX_TEXT_BUTTON *text_button = (GX_TEXT_BUTTON *) button;
    GX_CHECKBOX_PROPERTIES *props = (GX_CHECKBOX_PROPERTIES *) info->properties;
    status = gx_checkbox_create(button, info->widget_name, parent, props->string_id, info->style, info->widget_id, &info->size);
    if (status == GX_SUCCESS)
    {
        gx_text_button_font_set(text_button, props->font_id);
        gx_text_button_text_color_set(text_button, props->normal_text_color_id, props->selected_text_color_id);

        if (props->unchecked_pixelmap_id ||
            props->checked_pixelmap_id ||
            props->unchecked_disabled_pixelmap_id ||
            props->checked_disabled_pixelmap_id)
        {
            gx_checkbox_pixelmap_set(button,
                                     props->unchecked_pixelmap_id,
                                     props->checked_pixelmap_id,
                                     props->unchecked_disabled_pixelmap_id,
                                     props->checked_disabled_pixelmap_id);
        }
    }
    return status;
}

UINT gx_studio_pixelmap_button_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_PIXELMAP_BUTTON *button = (GX_PIXELMAP_BUTTON *) control_block;
    GX_PIXELMAP_BUTTON_PROPERTIES *props = (GX_PIXELMAP_BUTTON_PROPERTIES *) info->properties;
    status = gx_pixelmap_button_create(button, info->widget_name, parent,
               props->normal_pixelmap_id,
               props->selected_pixelmap_id,
               props->disabled_pixelmap_id,
               info->style, info->widget_id, &info->size);
    return status;
}

UINT gx_studio_prompt_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_PROMPT *prompt = (GX_PROMPT *) control_block;
    GX_PROMPT_PROPERTIES *props = (GX_PROMPT_PROPERTIES *) info->properties;
    status = gx_prompt_create(prompt, info->widget_name, parent, props->string_id, info->style, info->widget_id, &info->size);
    if (status == GX_SUCCESS)
    {
        gx_prompt_font_set(prompt, props->font_id);
        gx_prompt_text_color_set(prompt, props->normal_text_color_id, props->selected_text_color_id);
    }
    return status;
}

UINT gx_studio_window_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_WINDOW *window = (GX_WINDOW *) control_block;
    GX_WINDOW_PROPERTIES *props = (GX_WINDOW_PROPERTIES *) info->properties;
    status = gx_window_create(window, info->widget_name, parent, info->style, info->widget_id, &info->size);
    if (status == GX_SUCCESS)
    {
        if (props->wallpaper_id)
        {
            gx_window_wallpaper_set(window, props->wallpaper_id, info->style & GX_STYLE_TILE_WALLPAPER);
        }
    }
    return status;
}

UINT gx_studio_multi_line_text_view_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_MULTI_LINE_TEXT_VIEW *view = (GX_MULTI_LINE_TEXT_VIEW *) control_block;
    GX_ML_TEXT_VIEW_PROPERTIES *props = (GX_ML_TEXT_VIEW_PROPERTIES *) info->properties;
    status = gx_multi_line_text_view_create(view, info->widget_name, parent, props->string_id, info->style, info->widget_id, &info->size);
    if (status == GX_SUCCESS)
    {
        gx_multi_line_text_view_font_set(view, props->font_id);
        gx_multi_line_text_view_text_color_set(view, props->normal_text_color_id, props->selected_text_color_id);
    }
    return status;
}
GX_WINDOW_PROPERTIES warning_window_properties =
{
    0                                        /* wallpaper pixelmap id          */
};
GX_PROMPT_PROPERTIES warning_window_title_properties =
{
    GX_STRING_ID_STRING_40,                  /* string id                      */
    GX_FONT_ID_BIG,                          /* font id                        */
    GX_COLOR_ID_ORANGE,                      /* normal text color              */
    GX_COLOR_ID_ORANGE                       /* selected text color            */
};
GX_ML_TEXT_VIEW_PROPERTIES warning_window_alert_properties =
{
    GX_STRING_ID_STRING_42,                  /* string id                      */
    GX_FONT_ID_MEDIUM,                       /* font id                        */
    GX_COLOR_ID_ORANGE,                      /* normal text color              */
    GX_COLOR_ID_ORANGE                       /* selected text color            */
};

GX_CONST GX_STUDIO_WIDGET warning_window_alert_define =
{
    "alert",
    GX_TYPE_MULTI_LINE_TEXT_VIEW,            /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_DRAW_SELECTED|GX_STYLE_TEXT_CENTER,   /* style flags */
    0,                                       /* status flags                   */
    216,                                     /* control block size             */
    GX_COLOR_ID_TEXT,                        /* normal color id                */
    GX_COLOR_ID_TEXT,                        /* selected color id              */
    gx_studio_multi_line_text_view_create,     /* create function              */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {26, 100, 215, 269},                     /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(WARNING_WINDOW_CONTROL_BLOCK, warning_window_alert), /* control block */
    (void *) &warning_window_alert_properties /* extended properties           */
};

GX_CONST GX_STUDIO_WIDGET warning_window_title_define =
{
    "title",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TEXT_CENTER,   /* style flags                */
    0,                                       /* status flags                   */
    100,                                     /* control block size             */
    GX_COLOR_ID_TEXT,                        /* normal color id                */
    GX_COLOR_ID_TEXT,                        /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {25, 60, 214, 91},                       /* widget size                    */
    &warning_window_alert_define,            /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(WARNING_WINDOW_CONTROL_BLOCK, warning_window_title), /* control block */
    (void *) &warning_window_title_properties /* extended properties           */
};

GX_CONST GX_STUDIO_WIDGET warning_window_define =
{
    "warning_window",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THICK,                   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    104,                                     /* control block size             */
    GX_COLOR_ID_TEXT,                        /* normal color id                */
    GX_COLOR_ID_TEXT,                        /* selected color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {20, 40, 219, 279},                      /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &warning_window_title_define,            /* child widget                   */
    0,                                       /* control block                  */
    (void *) &warning_window_properties      /* extended properties            */
};
GX_WINDOW_PROPERTIES splash_properties =
{
    0                                        /* wallpaper pixelmap id          */
};
GX_PIXELMAP_BUTTON_PROPERTIES splash_pixelmap_button_1_properties =
{
    GX_PIXELMAP_ID_SYNERGY_LOGO_230X59,      /* normal pixelmap id             */
    0,                                       /* selected pixelmap id           */
    0                                        /* disabled pixelmap id           */
};

GX_CONST GX_STUDIO_WIDGET splash_pixelmap_button_1_define =
{
    "pixelmap_button_1",
    GX_TYPE_PIXELMAP_BUTTON,                 /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_HALIGN_CENTER,   /* style flags              */
    0,                                       /* status flags                   */
    96,                                      /* control block size             */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    gx_studio_pixelmap_button_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {0, 20, 239, 79},                        /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(SPLASH_CONTROL_BLOCK, splash_pixelmap_button_1), /* control block */
    (void *) &splash_pixelmap_button_1_properties /* extended properties       */
};

GX_CONST GX_STUDIO_WIDGET splash_define =
{
    "splash",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN,                    /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    104,                                     /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    (UINT (*)(GX_WIDGET *, GX_EVENT *)) SplashEventHandler, /* event function override */
    {0, 0, 255, 319},                        /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &splash_pixelmap_button_1_define,        /* child widget                   */
    0,                                       /* control block                  */
    (void *) &splash_properties              /* extended properties            */
};
GX_WINDOW_PROPERTIES alert_window_properties =
{
    0                                        /* wallpaper pixelmap id          */
};
GX_PROMPT_PROPERTIES alert_window_alert1_properties =
{
    GX_STRING_ID_STRING_29,                  /* string id                      */
    GX_FONT_ID_BIG,                          /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES alert_window_alert2_properties =
{
    GX_STRING_ID_STRING_33,                  /* string id                      */
    GX_FONT_ID_MEDIUM,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES alert_window_alert3_properties =
{
    GX_STRING_ID_STRING_32,                  /* string id                      */
    GX_FONT_ID_MEDIUM,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};

GX_CONST GX_STUDIO_WIDGET alert_window_alert3_define =
{
    "alert3",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TEXT_CENTER,   /* style flags                */
    0,                                       /* status flags                   */
    100,                                     /* control block size             */
    GX_COLOR_ID_RED,                         /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {25, 190, 214, 221},                     /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(ALERT_WINDOW_CONTROL_BLOCK, alert_window_alert3), /* control block */
    (void *) &alert_window_alert3_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET alert_window_alert2_define =
{
    "alert2",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TEXT_CENTER,   /* style flags                */
    0,                                       /* status flags                   */
    100,                                     /* control block size             */
    GX_COLOR_ID_RED,                         /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {25, 150, 214, 181},                     /* widget size                    */
    &alert_window_alert3_define,             /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(ALERT_WINDOW_CONTROL_BLOCK, alert_window_alert2), /* control block */
    (void *) &alert_window_alert2_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET alert_window_alert1_define =
{
    "alert1",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TEXT_CENTER,   /* style flags                */
    0,                                       /* status flags                   */
    100,                                     /* control block size             */
    GX_COLOR_ID_RED,                         /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {25, 100, 214, 131},                     /* widget size                    */
    &alert_window_alert2_define,             /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(ALERT_WINDOW_CONTROL_BLOCK, alert_window_alert1), /* control block */
    (void *) &alert_window_alert1_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET alert_window_define =
{
    "alert_window",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THICK,                   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    104,                                     /* control block size             */
    GX_COLOR_ID_RED,                         /* normal color id                */
    GX_COLOR_ID_RED,                         /* selected color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    (UINT (*)(GX_WIDGET *, GX_EVENT *)) AlertWindowEventHandler, /* event function override */
    {20, 80, 219, 239},                      /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &alert_window_alert1_define,             /* child widget                   */
    0,                                       /* control block                  */
    (void *) &alert_window_properties        /* extended properties            */
};
GX_WINDOW_PROPERTIES ams_window_properties =
{
    0                                        /* wallpaper pixelmap id          */
};
GX_TEXT_BUTTON_PROPERTIES ams_window_main_properties =
{
    GX_STRING_ID_STRING_12,                  /* string id                      */
    GX_FONT_ID_MEDIUM,                       /* font id                        */
    GX_COLOR_ID_BTN_TEXT,                    /* normal text color              */
    GX_COLOR_ID_BTN_TEXT                     /* selected text color            */
};
GX_PROMPT_PROPERTIES ams_window_humidity_prompt_properties =
{
    GX_STRING_ID_STRING_24,                  /* string id                      */
    GX_FONT_ID_NORMAL,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES ams_window_temperature_prompt_properties =
{
    GX_STRING_ID_STRING_25,                  /* string id                      */
    GX_FONT_ID_NORMAL,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES ams_window_humidity_value_properties =
{
    GX_STRING_ID_STRING_26,                  /* string id                      */
    GX_FONT_ID_MEDIUM,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES ams_window_temperature_value_properties =
{
    GX_STRING_ID_STRING_35,                  /* string id                      */
    GX_FONT_ID_MEDIUM,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES ams_window_Vibration_properties =
{
    GX_STRING_ID_STRING_43,                  /* string id                      */
    GX_FONT_ID_NORMAL,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES ams_window_Vibration_value_properties =
{
    GX_STRING_ID_STRING_44,                  /* string id                      */
    GX_FONT_ID_MEDIUM,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES ams_window_latitude_properties =
{
    GX_STRING_ID_STRING_45,                  /* string id                      */
    GX_FONT_ID_NORMAL,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES ams_window_Latitude_value_properties =
{
    GX_STRING_ID_STRING_46,                  /* string id                      */
    GX_FONT_ID_MEDIUM,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES ams_window_Longitude_properties =
{
    GX_STRING_ID_STRING_47,                  /* string id                      */
    GX_FONT_ID_NORMAL,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES ams_window_Longitude_value_properties =
{
    GX_STRING_ID_STRING_48,                  /* string id                      */
    GX_FONT_ID_MEDIUM,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};

GX_CONST GX_STUDIO_WIDGET ams_window_Longitude_value_define =
{
    "Longitude_value",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    100,                                     /* control block size             */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {133, 178, 224, 204},                    /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(AMS_WINDOW_CONTROL_BLOCK, ams_window_Longitude_value), /* control block */
    (void *) &ams_window_Longitude_value_properties /* extended properties     */
};

GX_CONST GX_STUDIO_WIDGET ams_window_Longitude_define =
{
    "Longitude",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    100,                                     /* control block size             */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {24, 181, 115, 204},                     /* widget size                    */
    &ams_window_Longitude_value_define,      /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(AMS_WINDOW_CONTROL_BLOCK, ams_window_Longitude), /* control block */
    (void *) &ams_window_Longitude_properties /* extended properties           */
};

GX_CONST GX_STUDIO_WIDGET ams_window_Latitude_value_define =
{
    "Latitude_value",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    100,                                     /* control block size             */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {129, 139, 229, 162},                    /* widget size                    */
    &ams_window_Longitude_define,            /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(AMS_WINDOW_CONTROL_BLOCK, ams_window_Latitude_value), /* control block */
    (void *) &ams_window_Latitude_value_properties /* extended properties      */
};

GX_CONST GX_STUDIO_WIDGET ams_window_latitude_define =
{
    "latitude",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    100,                                     /* control block size             */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {25, 141, 108, 164},                     /* widget size                    */
    &ams_window_Latitude_value_define,       /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(AMS_WINDOW_CONTROL_BLOCK, ams_window_latitude), /* control block  */
    (void *) &ams_window_latitude_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET ams_window_Vibration_value_define =
{
    "Vibration_value",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    100,                                     /* control block size             */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {129, 102, 230, 125},                    /* widget size                    */
    &ams_window_latitude_define,             /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(AMS_WINDOW_CONTROL_BLOCK, ams_window_Vibration_value), /* control block */
    (void *) &ams_window_Vibration_value_properties /* extended properties     */
};

GX_CONST GX_STUDIO_WIDGET ams_window_Vibration_define =
{
    "Vibration",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    100,                                     /* control block size             */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {24, 100, 119, 123},                     /* widget size                    */
    &ams_window_Vibration_value_define,      /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(AMS_WINDOW_CONTROL_BLOCK, ams_window_Vibration), /* control block */
    (void *) &ams_window_Vibration_properties /* extended properties           */
};

GX_CONST GX_STUDIO_WIDGET ams_window_temperature_value_define =
{
    "temperature_value",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TEXT_CENTER,   /* style flags                */
    0,                                       /* status flags                   */
    100,                                     /* control block size             */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {135, 55, 240, 86},                      /* widget size                    */
    &ams_window_Vibration_define,            /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(AMS_WINDOW_CONTROL_BLOCK, ams_window_temperature_value), /* control block */
    (void *) &ams_window_temperature_value_properties /* extended properties   */
};

GX_CONST GX_STUDIO_WIDGET ams_window_humidity_value_define =
{
    "humidity_value",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TEXT_CENTER,   /* style flags                */
    0,                                       /* status flags                   */
    100,                                     /* control block size             */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {134, 20, 218, 50},                      /* widget size                    */
    &ams_window_temperature_value_define,    /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(AMS_WINDOW_CONTROL_BLOCK, ams_window_humidity_value), /* control block */
    (void *) &ams_window_humidity_value_properties /* extended properties      */
};

GX_CONST GX_STUDIO_WIDGET ams_window_temperature_prompt_define =
{
    "temperature_prompt",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TEXT_LEFT,   /* style flags                  */
    0,                                       /* status flags                   */
    100,                                     /* control block size             */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {21, 57, 130, 80},                       /* widget size                    */
    &ams_window_humidity_value_define,       /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(AMS_WINDOW_CONTROL_BLOCK, ams_window_temperature_prompt), /* control block */
    (void *) &ams_window_temperature_prompt_properties /* extended properties  */
};

GX_CONST GX_STUDIO_WIDGET ams_window_humidity_prompt_define =
{
    "humidity_prompt",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TEXT_LEFT,   /* style flags                  */
    0,                                       /* status flags                   */
    100,                                     /* control block size             */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {22, 21, 115, 44},                       /* widget size                    */
    &ams_window_temperature_prompt_define,   /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(AMS_WINDOW_CONTROL_BLOCK, ams_window_humidity_prompt), /* control block */
    (void *) &ams_window_humidity_prompt_properties /* extended properties     */
};

GX_CONST GX_STUDIO_WIDGET ams_window_main_define =
{
    "main",
    GX_TYPE_TEXT_BUTTON,                     /* widget type                    */
    IDB_AMS_MAIN_BTN,                        /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THICK|GX_STYLE_ENABLED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    104,                                     /* control block size             */
    GX_COLOR_ID_BTN_BORDER,                  /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    gx_studio_text_button_create,            /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {82, 261, 161, 312},                     /* widget size                    */
    &ams_window_humidity_prompt_define,      /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(AMS_WINDOW_CONTROL_BLOCK, ams_window_main), /* control block      */
    (void *) &ams_window_main_properties     /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET ams_window_define =
{
    "ams_window",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE,                    /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    104,                                     /* control block size             */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    (UINT (*)(GX_WIDGET *, GX_EVENT *)) AMSWindowEventHandler, /* event function override */
    {2, 1, 257, 320},                        /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &ams_window_main_define,                 /* child widget                   */
    0,                                       /* control block                  */
    (void *) &ams_window_properties          /* extended properties            */
};
GX_WINDOW_PROPERTIES s7_window_properties =
{
    0                                        /* wallpaper pixelmap id          */
};
GX_TEXT_BUTTON_PROPERTIES s7_window_AMS_properties =
{
    GX_STRING_ID_STRING_8,                   /* string id                      */
    GX_FONT_ID_MEDIUM,                       /* font id                        */
    GX_COLOR_ID_BTN_TEXT,                    /* normal text color              */
    GX_COLOR_ID_BTN_TEXT                     /* selected text color            */
};
GX_TEXT_BUTTON_PROPERTIES s7_window_Main_properties =
{
    GX_STRING_ID_STRING_12,                  /* string id                      */
    GX_FONT_ID_MEDIUM,                       /* font id                        */
    GX_COLOR_ID_BTN_TEXT,                    /* normal text color              */
    GX_COLOR_ID_BTN_TEXT                     /* selected text color            */
};
GX_CHECKBOX_PROPERTIES s7_window_led_1_properties =
{
    GX_STRING_ID_STRING_13,                  /* string id                      */
    GX_FONT_ID_BUTTON,                       /* font id                        */
    GX_COLOR_ID_BTN_TEXT,                    /* normal text color              */
    GX_COLOR_ID_BTN_TEXT,                    /* selected text color            */
    0,                                       /* unchecked pixelmap id          */
    0,                                       /* checked pixelmap id            */
    0,                                       /* unchecked disabled pixelmap id */
    0                                        /* checked disabled pixelmap id   */
};
GX_CHECKBOX_PROPERTIES s7_window_led_2_properties =
{
    GX_STRING_ID_STRING_14,                  /* string id                      */
    GX_FONT_ID_BUTTON,                       /* font id                        */
    GX_COLOR_ID_BTN_TEXT,                    /* normal text color              */
    GX_COLOR_ID_BTN_TEXT,                    /* selected text color            */
    0,                                       /* unchecked pixelmap id          */
    0,                                       /* checked pixelmap id            */
    0,                                       /* unchecked disabled pixelmap id */
    0                                        /* checked disabled pixelmap id   */
};
GX_CHECKBOX_PROPERTIES s7_window_led_3_properties =
{
    GX_STRING_ID_STRING_15,                  /* string id                      */
    GX_FONT_ID_BUTTON,                       /* font id                        */
    GX_COLOR_ID_BTN_TEXT,                    /* normal text color              */
    GX_COLOR_ID_BTN_TEXT,                    /* selected text color            */
    0,                                       /* unchecked pixelmap id          */
    0,                                       /* checked pixelmap id            */
    0,                                       /* unchecked disabled pixelmap id */
    0                                        /* checked disabled pixelmap id   */
};
GX_CHECKBOX_PROPERTIES s7_window_led_blink_properties =
{
    GX_STRING_ID_STRING_17,                  /* string id                      */
    GX_FONT_ID_BUTTON,                       /* font id                        */
    GX_COLOR_ID_BTN_TEXT,                    /* normal text color              */
    GX_COLOR_ID_BTN_TEXT,                    /* selected text color            */
    0,                                       /* unchecked pixelmap id          */
    0,                                       /* checked pixelmap id            */
    0,                                       /* unchecked disabled pixelmap id */
    0                                        /* checked disabled pixelmap id   */
};
GX_PROMPT_PROPERTIES s7_window_sw1_prompt_properties =
{
    GX_STRING_ID_STRING_18,                  /* string id                      */
    GX_FONT_ID_BUTTON,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES s7_window_sw2_prompt_properties =
{
    GX_STRING_ID_STRING_19,                  /* string id                      */
    GX_FONT_ID_BUTTON,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES s7_window_sw1_count_properties =
{
    GX_STRING_ID_STRING_20,                  /* string id                      */
    GX_FONT_ID_BUTTON,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES s7_window_sw2_count_properties =
{
    GX_STRING_ID_STRING_20,                  /* string id                      */
    GX_FONT_ID_BUTTON,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES s7_window_temp_prompt_properties =
{
    GX_STRING_ID_STRING_21,                  /* string id                      */
    GX_FONT_ID_BUTTON,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES s7_window_uptime_prompt_properties =
{
    GX_STRING_ID_STRING_22,                  /* string id                      */
    GX_FONT_ID_BUTTON,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES s7_window_temp_count_properties =
{
    GX_STRING_ID_STRING_23,                  /* string id                      */
    GX_FONT_ID_BUTTON,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES s7_window_uptime_count_properties =
{
    GX_STRING_ID_STRING_20,                  /* string id                      */
    GX_FONT_ID_BUTTON,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};

GX_CONST GX_STUDIO_WIDGET s7_window_uptime_count_define =
{
    "uptime_count",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TEXT_LEFT,   /* style flags                  */
    0,                                       /* status flags                   */
    100,                                     /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {120, 230, 219, 253},                    /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(S7_WINDOW_CONTROL_BLOCK, s7_window_uptime_count), /* control block */
    (void *) &s7_window_uptime_count_properties /* extended properties         */
};

GX_CONST GX_STUDIO_WIDGET s7_window_temp_count_define =
{
    "temp_count",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TEXT_LEFT,   /* style flags                  */
    0,                                       /* status flags                   */
    100,                                     /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {120, 200, 219, 223},                    /* widget size                    */
    &s7_window_uptime_count_define,          /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(S7_WINDOW_CONTROL_BLOCK, s7_window_temp_count), /* control block  */
    (void *) &s7_window_temp_count_properties /* extended properties           */
};

GX_CONST GX_STUDIO_WIDGET s7_window_uptime_prompt_define =
{
    "uptime_prompt",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TEXT_RIGHT,   /* style flags                 */
    0,                                       /* status flags                   */
    100,                                     /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {20, 230, 109, 253},                     /* widget size                    */
    &s7_window_temp_count_define,            /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(S7_WINDOW_CONTROL_BLOCK, s7_window_uptime_prompt), /* control block */
    (void *) &s7_window_uptime_prompt_properties /* extended properties        */
};

GX_CONST GX_STUDIO_WIDGET s7_window_temp_prompt_define =
{
    "temp_prompt",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TEXT_RIGHT,   /* style flags                 */
    0,                                       /* status flags                   */
    100,                                     /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {20, 200, 109, 223},                     /* widget size                    */
    &s7_window_uptime_prompt_define,         /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(S7_WINDOW_CONTROL_BLOCK, s7_window_temp_prompt), /* control block */
    (void *) &s7_window_temp_prompt_properties /* extended properties          */
};

GX_CONST GX_STUDIO_WIDGET s7_window_sw2_count_define =
{
    "sw2_count",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TEXT_LEFT,   /* style flags                  */
    0,                                       /* status flags                   */
    100,                                     /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {120, 140, 219, 163},                    /* widget size                    */
    &s7_window_temp_prompt_define,           /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(S7_WINDOW_CONTROL_BLOCK, s7_window_sw2_count), /* control block   */
    (void *) &s7_window_sw2_count_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET s7_window_sw1_count_define =
{
    "sw1_count",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TEXT_LEFT,   /* style flags                  */
    0,                                       /* status flags                   */
    100,                                     /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {120, 110, 219, 133},                    /* widget size                    */
    &s7_window_sw2_count_define,             /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(S7_WINDOW_CONTROL_BLOCK, s7_window_sw1_count), /* control block   */
    (void *) &s7_window_sw1_count_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET s7_window_sw2_prompt_define =
{
    "sw2_prompt",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TEXT_RIGHT,   /* style flags                 */
    0,                                       /* status flags                   */
    100,                                     /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {20, 140, 109, 163},                     /* widget size                    */
    &s7_window_sw1_count_define,             /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(S7_WINDOW_CONTROL_BLOCK, s7_window_sw2_prompt), /* control block  */
    (void *) &s7_window_sw2_prompt_properties /* extended properties           */
};

GX_CONST GX_STUDIO_WIDGET s7_window_sw1_prompt_define =
{
    "sw1_prompt",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TEXT_RIGHT,   /* style flags                 */
    0,                                       /* status flags                   */
    100,                                     /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {20, 110, 109, 133},                     /* widget size                    */
    &s7_window_sw2_prompt_define,            /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(S7_WINDOW_CONTROL_BLOCK, s7_window_sw1_prompt), /* control block  */
    (void *) &s7_window_sw1_prompt_properties /* extended properties           */
};

GX_CONST GX_STUDIO_WIDGET s7_window_led_blink_define =
{
    "led_blink",
    GX_TYPE_CHECKBOX,                        /* widget type                    */
    IDB_LED_BLINK_BTN,                       /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_BUTTON_TOGGLE|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    120,                                     /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    gx_studio_checkbox_create,               /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {140, 50, 219, 73},                      /* widget size                    */
    &s7_window_sw1_prompt_define,            /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(S7_WINDOW_CONTROL_BLOCK, s7_window_led_blink), /* control block   */
    (void *) &s7_window_led_blink_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET s7_window_led_3_define =
{
    "led_3",
    GX_TYPE_CHECKBOX,                        /* widget type                    */
    IDB_LED3_BTN,                            /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_BUTTON_TOGGLE|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    120,                                     /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    gx_studio_checkbox_create,               /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {20, 50, 99, 73},                        /* widget size                    */
    &s7_window_led_blink_define,             /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(S7_WINDOW_CONTROL_BLOCK, s7_window_led_3), /* control block       */
    (void *) &s7_window_led_3_properties     /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET s7_window_led_2_define =
{
    "led_2",
    GX_TYPE_CHECKBOX,                        /* widget type                    */
    IDB_LED2_BTN,                            /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_BUTTON_TOGGLE|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    120,                                     /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    gx_studio_checkbox_create,               /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {140, 20, 219, 43},                      /* widget size                    */
    &s7_window_led_3_define,                 /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(S7_WINDOW_CONTROL_BLOCK, s7_window_led_2), /* control block       */
    (void *) &s7_window_led_2_properties     /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET s7_window_led_1_define =
{
    "led_1",
    GX_TYPE_CHECKBOX,                        /* widget type                    */
    IDB_LED1_BTN,                            /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_BUTTON_TOGGLE|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    120,                                     /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    gx_studio_checkbox_create,               /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {20, 20, 99, 43},                        /* widget size                    */
    &s7_window_led_2_define,                 /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(S7_WINDOW_CONTROL_BLOCK, s7_window_led_1), /* control block       */
    (void *) &s7_window_led_1_properties     /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET s7_window_Main_define =
{
    "Main",
    GX_TYPE_TEXT_BUTTON,                     /* widget type                    */
    IDB_S7_MAIN_BTN,                         /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    104,                                     /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    gx_studio_text_button_create,            /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {140, 280, 219, 311},                    /* widget size                    */
    &s7_window_led_1_define,                 /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(S7_WINDOW_CONTROL_BLOCK, s7_window_Main), /* control block        */
    (void *) &s7_window_Main_properties      /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET s7_window_AMS_define =
{
    "AMS",
    GX_TYPE_TEXT_BUTTON,                     /* widget type                    */
    IDB_S7_AMS_BTN,                          /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THICK|GX_STYLE_ENABLED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    104,                                     /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    gx_studio_text_button_create,            /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {20, 280, 99, 311},                      /* widget size                    */
    &s7_window_Main_define,                  /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(S7_WINDOW_CONTROL_BLOCK, s7_window_AMS), /* control block         */
    (void *) &s7_window_AMS_properties       /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET s7_window_define =
{
    "s7_window",
    GX_TYPE_WINDOW,                          /* widget type                    */
    IDB_S7_WINDOW,                           /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE,                    /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    104,                                     /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    (UINT (*)(GX_WIDGET *, GX_EVENT *)) S7WindowEventHandler, /* event function override */
    {0, 0, 255, 319},                        /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &s7_window_AMS_define,                   /* child widget                   */
    0,                                       /* control block                  */
    (void *) &s7_window_properties           /* extended properties            */
};
GX_WINDOW_PROPERTIES main_window_properties =
{
    0                                        /* wallpaper pixelmap id          */
};
GX_PROMPT_PROPERTIES main_window_title_properties =
{
    GX_STRING_ID_STRING_2,                   /* string id                      */
    GX_FONT_ID_BIG,                          /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES main_window_thing_properties =
{
    GX_STRING_ID_STRING_10,                  /* string id                      */
    GX_FONT_ID_MEDIUM,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES main_window_info1_properties =
{
    GX_STRING_ID_STRING_38,                  /* string id                      */
    GX_FONT_ID_MEDIUM,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_TEXT_BUTTON_PROPERTIES main_window_AMS_properties =
{
    GX_STRING_ID_STRING_8,                   /* string id                      */
    GX_FONT_ID_MEDIUM,                       /* font id                        */
    GX_COLOR_ID_BTN_TEXT,                    /* normal text color              */
    GX_COLOR_ID_BTN_TEXT                     /* selected text color            */
};
GX_PROMPT_PROPERTIES main_window_info2_properties =
{
    GX_STRING_ID_STRING_34,                  /* string id                      */
    GX_FONT_ID_MEDIUM,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES main_window_url_properties =
{
    GX_STRING_ID_STRING_39,                  /* string id                      */
    GX_FONT_ID_NORMAL,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};
GX_PROMPT_PROPERTIES main_window_info3_properties =
{
    GX_STRING_ID_STRING_3,                   /* string id                      */
    GX_FONT_ID_NORMAL,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT                /* selected text color            */
};

GX_CONST GX_STUDIO_WIDGET main_window_info3_define =
{
    "info3",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TEXT_CENTER,   /* style flags                */
    0,                                       /* status flags                   */
    100,                                     /* control block size             */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {20, 230, 219, 253},                     /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(MAIN_WINDOW_CONTROL_BLOCK, main_window_info3), /* control block   */
    (void *) &main_window_info3_properties   /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET main_window_url_define =
{
    "url",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TEXT_CENTER,   /* style flags                */
    0,                                       /* status flags                   */
    100,                                     /* control block size             */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {0, 60, 239, 83},                        /* widget size                    */
    &main_window_info3_define,               /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(MAIN_WINDOW_CONTROL_BLOCK, main_window_url), /* control block     */
    (void *) &main_window_url_properties     /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET main_window_info2_define =
{
    "info2",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TEXT_CENTER,   /* style flags                */
    0,                                       /* status flags                   */
    100,                                     /* control block size             */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {20, 200, 219, 223},                     /* widget size                    */
    &main_window_url_define,                 /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(MAIN_WINDOW_CONTROL_BLOCK, main_window_info2), /* control block   */
    (void *) &main_window_info2_properties   /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET main_window_AMS_define =
{
    "AMS",
    GX_TYPE_TEXT_BUTTON,                     /* widget type                    */
    IDB_MAIN_AMS_BTN,                        /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THICK|GX_STYLE_ENABLED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    104,                                     /* control block size             */
    GX_COLOR_ID_BTN_BORDER,                  /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    gx_studio_text_button_create,            /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {80, 260, 159, 311},                     /* widget size                    */
    &main_window_info2_define,               /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(MAIN_WINDOW_CONTROL_BLOCK, main_window_AMS), /* control block     */
    (void *) &main_window_AMS_properties     /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET main_window_info1_define =
{
    "info1",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TEXT_CENTER,   /* style flags                */
    0,                                       /* status flags                   */
    100,                                     /* control block size             */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {20, 170, 219, 193},                     /* widget size                    */
    &main_window_AMS_define,                 /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(MAIN_WINDOW_CONTROL_BLOCK, main_window_info1), /* control block   */
    (void *) &main_window_info1_properties   /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET main_window_thing_define =
{
    "thing",
    GX_TYPE_PROMPT,                          /* widget type                    */
    IDB_INFO_TEXT,                           /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TEXT_CENTER,   /* style flags                */
    0,                                       /* status flags                   */
    100,                                     /* control block size             */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {20, 100, 219, 123},                     /* widget size                    */
    &main_window_info1_define,               /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(MAIN_WINDOW_CONTROL_BLOCK, main_window_thing), /* control block   */
    (void *) &main_window_thing_properties   /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET main_window_title_define =
{
    "title",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TEXT_CENTER,   /* style flags                */
    0,                                       /* status flags                   */
    100,                                     /* control block size             */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {20, 20, 219, 51},                       /* widget size                    */
    &main_window_thing_define,               /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(MAIN_WINDOW_CONTROL_BLOCK, main_window_title), /* control block   */
    (void *) &main_window_title_properties   /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET main_window_define =
{
    "main_window",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE,                    /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    104,                                     /* control block size             */
    GX_COLOR_ID_SELECTED_TEXT,               /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    (UINT (*)(GX_WIDGET *, GX_EVENT *)) MainWindowEventHandler, /* event function override */
    {0, 0, 255, 319},                        /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &main_window_title_define,               /* child widget                   */
    0,                                       /* control block                  */
    (void *) &main_window_properties         /* extended properties            */
};
GX_CONST GX_STUDIO_WIDGET_ENTRY SmartWine_widget_table[] =
{
    { &warning_window_define, (GX_WIDGET *) &warning_window },
    { &splash_define, (GX_WIDGET *) &splash },
    { &alert_window_define, (GX_WIDGET *) &alert_window },
    { &ams_window_define, (GX_WIDGET *) &ams_window },
    { &s7_window_define, (GX_WIDGET *) &s7_window },
    { &main_window_define, (GX_WIDGET *) &main_window },
    {GX_NULL, GX_NULL}
};

UINT gx_studio_widget_create(GX_BYTE *control, GX_CONST GX_STUDIO_WIDGET *definition, GX_WIDGET *parent)
{
    UINT status = GX_SUCCESS;
    GX_WIDGET *widget = GX_NULL;

    while(definition && status == GX_SUCCESS)
    {
        if (definition->create_function)
        {
            if (definition->style & GX_STYLE_DYNAMICALLY_ALLOCATED)
            {
                status = gx_widget_allocate(&widget, definition->control_block_size);
                if (status != GX_SUCCESS)
                {
                    return GX_NULL;
                }
            }
            else
            {
                if(!control)
                {
                    return GX_NULL;
                }

                widget = (GX_WIDGET *) (control + definition->control_block_offset);
            }

            status = definition->create_function(definition, widget, parent);

            if (status == GX_SUCCESS)
            {
                if (definition->widget_type != GX_TYPE_TEMPLATE)
                {
                    gx_widget_fill_color_set(widget, definition->normal_fill_color_id, definition->selected_fill_color_id);
                }

                if (!(definition->status & GX_STATUS_ACCEPTS_FOCUS))
                {
                    gx_widget_status_remove(widget, GX_STATUS_ACCEPTS_FOCUS);
                }

                if (definition->draw_function)
                {
                    gx_widget_draw_set(widget, definition->draw_function);
                }
                if (definition->event_function)
                {
                    gx_widget_event_process_set(widget, definition->event_function);
                }

                #if defined(GX_WIDGET_USER_DATA)
                widget->gx_widget_user_data = definition->user_data;
                #endif

                if (definition->child_widget)
                {
                    gx_studio_widget_create(control, definition->child_widget, widget);
                }
            }
            definition = definition->next_widget;
        }
    }
    return status;
}


UINT gx_studio_named_widget_create(char *name, GX_WIDGET *parent, GX_WIDGET **new_widget)
{
    UINT status = GX_FAILURE;
    GX_CONST GX_STUDIO_WIDGET_ENTRY *entry = SmartWine_widget_table;
    GX_WIDGET *control_block = GX_NULL;

    while(entry->widget_information)
    {
        if (!strcmp(name, entry->widget_information->widget_name))
        {
            control_block = entry->widget;
            status = gx_studio_widget_create((GX_BYTE *) control_block, entry->widget_information, parent);
            break;
        }
        entry++;
    }

    if (new_widget)
    {
        *new_widget = control_block;
    }
    return status;
}


GX_DISPLAY display_1_control_block;
GX_CANVAS  display_1_canvas_control_block;
GX_WINDOW_ROOT display_1_root_window;

GX_DISPLAY display_1_control_block;
GX_CANVAS  display_1_canvas_control_block;
GX_WINDOW_ROOT display_1_root_window;
extern GX_CONST GX_THEME *display_1_theme_table[];
extern GX_CONST GX_CHAR **display_1_language_table[];

GX_STUDIO_DISPLAY_INFO SmartWine_display_table[1] =
{
    {
    "display_1",
    "display_1_canvas",
    display_1_theme_table,
    display_1_language_table,
    DISPLAY_1_LANGUAGE_TABLE_SIZE,
    DISPLAY_1_STRING_TABLE_SIZE,
    256,                                     /* x resolution                   */
    320,                                     /* y resolution                   */
    &display_1_control_block,
    &display_1_canvas_control_block,
    &display_1_root_window,
    GX_NULL,                                 /* canvas memory area             */
    163840                                   /* canvas memory size in bytes    */
    }
};

UINT gx_studio_display_configure(USHORT display, UINT (*driver)(GX_DISPLAY *),
    USHORT language, USHORT theme, GX_WINDOW_ROOT **return_root)
{
    GX_CONST GX_THEME *theme_ptr;
    GX_RECTANGLE size;

    GX_STUDIO_DISPLAY_INFO *display_info = &SmartWine_display_table[display];


/* create the requested display                                                */

    gx_display_create(display_info->display,
                      display_info->name,
                      driver,
                      (GX_VALUE) display_info->x_resolution,
                      (GX_VALUE) display_info->y_resolution);


/* install the request theme                                                   */

    theme_ptr = SmartWine_display_table[display].theme_table[theme];
    gx_display_color_table_set(display_info->display, theme_ptr->theme_color_table, theme_ptr->theme_color_table_size);
    
/* install the color palette if required                                       */
    if (display_info->display->gx_display_driver_palette_set &&
        theme_ptr->theme_palette != NULL)
    {
        display_info->display->gx_display_driver_palette_set(display_info->display, theme_ptr->theme_palette, theme_ptr->theme_palette_size);
    }

    gx_display_font_table_set(display_info->display, theme_ptr->theme_font_table, theme_ptr->theme_font_table_size);
    gx_display_pixelmap_table_set(display_info->display, theme_ptr->theme_pixelmap_table, theme_ptr->theme_pixelmap_table_size);
    gx_system_scroll_appearance_set(theme_ptr->theme_vertical_scroll_style, (GX_SCROLLBAR_APPEARANCE *) &theme_ptr->theme_vertical_scrollbar_appearance);
    gx_system_scroll_appearance_set(theme_ptr->theme_horizontal_scroll_style, (GX_SCROLLBAR_APPEARANCE *) &theme_ptr->theme_horizontal_scrollbar_appearance);
    gx_system_language_table_set((GX_CHAR ***) display_info->language_table, display_info->language_table_size, display_info->string_table_size);
    gx_system_active_language_set(language);


/* create the canvas for this display                                          */

    gx_canvas_create(display_info->canvas,
                     display_info->canvas_name,
                     display_info->display,
                     GX_CANVAS_MANAGED | GX_CANVAS_VISIBLE,
                     display_info->x_resolution,
                     display_info->y_resolution,
                     display_info->canvas_memory,
                     display_info->canvas_memory_size);

/* Create the root window for this canvas                                      */

    gx_utility_rectangle_define(&size,
                                0, 0,
                                (GX_VALUE) (display_info->x_resolution - 1),
                                (GX_VALUE) (display_info->y_resolution - 1));

    gx_window_root_create(display_info->root_window,
                          display_info->name,
                          display_info->canvas, GX_STYLE_NONE, 0, &size);
    if (return_root)
    {
        *return_root = display_info->root_window;
    }
    return GX_SUCCESS;
}

/* Provide display driver setup function                                       */

#if defined(GX_TARGET_WIN32) || defined(GX_TARGET_LINUX)

UINT _gx_synergy_display_driver_setup(GX_DISPLAY *display)
{
    win32_synergy_graphics_driver_setup_565rgb(display);
    return GX_SUCCESS;
}
#else
UINT _gx_synergy_display_driver_setup(GX_DISPLAY *display)
{
    _gx_display_driver_565rgb_setup(display, GX_NULL, _gx_dave2d_buffer_toggle);
    display->gx_display_handle =    0;
    display -> gx_display_driver_horizontal_pattern_line_draw  = _gx_dave2d_horizontal_pattern_line_draw_565;
    display -> gx_display_driver_vertical_pattern_line_draw    = _gx_dave2d_vertical_pattern_line_draw_565;
    display -> gx_display_driver_pixel_write                   = _gx_dave2d_pixel_write_565;
    display -> gx_display_driver_pixel_blend                   = _gx_dave2d_pixel_blend_565;
    display -> gx_display_driver_drawing_initiate              = _gx_dave2d_drawing_initiate;
    display -> gx_display_driver_drawing_complete              = _gx_dave2d_drawing_complete;
    display -> gx_display_driver_canvas_copy                   = _gx_dave2d_canvas_copy;
    display -> gx_display_driver_canvas_blend                  = _gx_dave2d_canvas_blend;
    display -> gx_display_driver_simple_line_draw              = _gx_dave2d_simple_line_draw;
    display -> gx_display_driver_horizontal_line_draw          = _gx_dave2d_horizontal_line;
    display -> gx_display_driver_vertical_line_draw            = _gx_dave2d_vertical_line;
    display -> gx_display_driver_polygon_draw                  = _gx_dave2d_polygon_draw;
    display -> gx_display_driver_polygon_fill                  = _gx_dave2d_polygon_fill;
    display -> gx_display_driver_block_move                    = _gx_dave2d_block_move;
    display -> gx_display_driver_pixelmap_draw                 = _gx_dave2d_pixelmap_draw;
    display -> gx_display_driver_horizontal_pixelmap_line_draw = _gx_dave2d_horizontal_pixelmap_line_draw;
    display -> gx_display_driver_alphamap_draw                 = _gx_dave2d_alphamap_draw;
    display -> gx_display_driver_simple_wide_line_draw         = _gx_dave2d_simple_wide_line;
    display -> gx_display_driver_anti_aliased_line_draw        = _gx_dave2d_aliased_line;
    display -> gx_display_driver_anti_aliased_wide_line_draw   = _gx_dave2d_aliased_wide_line;
    display -> gx_display_driver_pixelmap_blend                = _gx_dave2d_pixelmap_blend;
    display -> gx_display_driver_8bit_glyph_draw               = _gx_dave2d_glyph_8bit_draw;
    display -> gx_display_driver_4bit_glyph_draw               = _gx_dave2d_glyph_4bit_draw;
    display -> gx_display_driver_1bit_glyph_draw               = _gx_dave2d_glyph_1bit_draw;
    #if defined(GX_ARC_DRAWING_SUPPORT)
    display -> gx_display_driver_anti_aliased_circle_draw      = _gx_dave2d_aliased_circle_draw;
    display -> gx_display_driver_anti_aliased_wide_circle_draw = _gx_dave2d_aliased_circle_draw;
    display -> gx_display_driver_circle_draw                   = _gx_dave2d_circle_draw;
    display -> gx_display_driver_circle_fill                   = _gx_dave2d_circle_fill;
    display -> gx_display_driver_pie_fill                      = _gx_dave2d_pie_fill;
    display -> gx_display_driver_anti_aliased_arc_draw         = _gx_dave2d_aliased_arc_draw;
    display -> gx_display_driver_arc_draw                      = _gx_dave2d_arc_draw;
    display -> gx_display_driver_arc_fill                      = _gx_dave2d_arc_fill;
    display -> gx_display_driver_anti_aliased_ellipse_draw     = _gx_dave2d_aliased_ellipse_draw;
    display -> gx_display_driver_ellipse_draw                  = _gx_dave2d_ellipse_draw;
    display -> gx_display_driver_ellipse_fill                  = _gx_dave2d_ellipse_fill;
    display -> gx_display_driver_wide_circle_draw              = _gx_dave2d_circle_draw;
    display -> gx_display_driver_anti_aliased_wide_arc_draw    = _gx_dave2d_aliased_arc_draw;
    display -> gx_display_driver_wide_arc_draw                 = _gx_dave2d_arc_draw;
    #endif
    display -> gx_display_driver_png_draw                     = _gx_display_driver_565rgb_png_draw;
    return GX_SUCCESS;
}
#endif
#undef GUIX_STUDIO_GENERATED_FILE
