/*******************************************************************************/
/*  This file is auto-generated by GUIX Studio. Do not edit this file by hand. */
/*  Modifications to this file should only be made by running the GUIX Studio  */
/*  application and re-generating the application resource file(s). For more   */
/*  information please refer to the GUIX Studio user's guide, or visit our web */
/*  site at www.expresslogic.com.                                              */
/*                                                                             */
/*  GUIX Studio Revision 5.3.2.2                                               */
/*  Date (dd.mm.yyyy): 17. 4.2017   Time (hh:mm): 17:56                        */
/*******************************************************************************/


#ifndef _SMARTWINE_DISPLAY_1_RESOURCES_H_
#define _SMARTWINE_DISPLAY_1_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define DISPLAY_1 0
#define DISPLAY_1_COLOR_FORMAT GX_COLOR_FORMAT_565RGB
#define DISPLAY_1_X_RESOLUTION 256
#define DISPLAY_1_Y_RESOLUTION 320
#define DISPLAY_1_THEME_1 0

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define DISPLAY_1_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_CANVAS 0
#define GX_COLOR_ID_WIDGET_FILL 1
#define GX_COLOR_ID_WINDOW_FILL 2
#define GX_COLOR_ID_DEFAULT_BORDER 3
#define GX_COLOR_ID_WINDOW_BORDER 4
#define GX_COLOR_ID_TEXT 5
#define GX_COLOR_ID_SELECTED_TEXT 6
#define GX_COLOR_ID_SELECTED_FILL 7
#define GX_COLOR_ID_SHADOW 8
#define GX_COLOR_ID_SHINE 9
#define GX_COLOR_ID_BTN_BORDER 10
#define GX_COLOR_ID_BTN_UPPER 11
#define GX_COLOR_ID_BTN_LOWER 12
#define GX_COLOR_ID_BTN_TEXT 13
#define GX_COLOR_ID_SCROLL_FILL 14
#define GX_COLOR_ID_SCROLL_BUTTON 15
#define GX_COLOR_ID_TEXT_INPUT_TEXT 16
#define GX_COLOR_ID_TEXT_INPUT_FILL 17
#define GX_COLOR_ID_SLIDER_TICK 18
#define GX_COLOR_ID_SLIDER_GROOVE_TOP 19
#define GX_COLOR_ID_SLIDER_GROOVE_BOTTOM 20
#define GX_COLOR_ID_SLIDER_NEEDLE_OUTLINE 21
#define GX_COLOR_ID_SLIDER_NEEDLE_FILL 22
#define GX_COLOR_ID_SLIDER_NEEDLE_LINE1 23
#define GX_COLOR_ID_SLIDER_NEEDLE_LINE2 24
#define GX_COLOR_ID_RED 25
#define GX_COLOR_ID_ORANGE 26
#define DISPLAY_1_COLOR_TABLE_SIZE 27

/* Font ID definitions                                                         */

#define GX_FONT_ID_SYSTEM 0
#define GX_FONT_ID_BUTTON 1
#define GX_FONT_ID_PROMPT 2
#define GX_FONT_ID_TEXT_INPUT 3
#define GX_FONT_ID_BIG 4
#define GX_FONT_ID_MEDIUM 5
#define GX_FONT_ID_NORMAL 6
#define GX_FONT_ID_SMALL 7
#define DISPLAY_1_FONT_TABLE_SIZE 8

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_RADIO_ON 1
#define GX_PIXELMAP_ID_RADIO_OFF 2
#define GX_PIXELMAP_ID_CHECKBOX_ON 3
#define GX_PIXELMAP_ID_CHECKBOX_OFF 4
#define GX_PIXELMAP_ID_SYNERGY_LOGO_230X59 5
#define DISPLAY_1_PIXELMAP_TABLE_SIZE 6

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_1 1
#define GX_STRING_ID_STRING_2 2
#define GX_STRING_ID_STRING_3 3
#define GX_STRING_ID_STRING_4 4
#define GX_STRING_ID_STRING_5 5
#define GX_STRING_ID_STRING_6 6
#define GX_STRING_ID_STRING_7 7
#define GX_STRING_ID_STRING_8 8
#define GX_STRING_ID_STRING_9 9
#define GX_STRING_ID_STRING_10 10
#define GX_STRING_ID_STRING_11 11
#define GX_STRING_ID_STRING_12 12
#define GX_STRING_ID_STRING_13 13
#define GX_STRING_ID_STRING_14 14
#define GX_STRING_ID_STRING_15 15
#define GX_STRING_ID_STRING_16 16
#define GX_STRING_ID_STRING_17 17
#define GX_STRING_ID_STRING_18 18
#define GX_STRING_ID_STRING_19 19
#define GX_STRING_ID_STRING_20 20
#define GX_STRING_ID_STRING_21 21
#define GX_STRING_ID_STRING_22 22
#define GX_STRING_ID_STRING_23 23
#define GX_STRING_ID_STRING_24 24
#define GX_STRING_ID_STRING_25 25
#define GX_STRING_ID_STRING_26 26
#define GX_STRING_ID_STRING_27 27
#define GX_STRING_ID_STRING_28 28
#define GX_STRING_ID_STRING_29 29
#define GX_STRING_ID_STRING_30 30
#define GX_STRING_ID_STRING_31 31
#define GX_STRING_ID_STRING_32 32
#define GX_STRING_ID_STRING_33 33
#define GX_STRING_ID_STRING_34 34
#define GX_STRING_ID_STRING_35 35
#define GX_STRING_ID_STRING_36 36
#define GX_STRING_ID_STRING_37 37
#define GX_STRING_ID_STRING_38 38
#define GX_STRING_ID_STRING_39 39
#define GX_STRING_ID_STRING_40 40
#define GX_STRING_ID_STRING_41 41
#define GX_STRING_ID_STRING_42 42
#define GX_STRING_ID_STRING_43 43
#define GX_STRING_ID_STRING_44 44
#define GX_STRING_ID_STRING_45 45
#define GX_STRING_ID_STRING_46 46
#define GX_STRING_ID_STRING_47 47
#define GX_STRING_ID_STRING_48 48
#define DISPLAY_1_STRING_TABLE_SIZE 49

#endif                                       /* sentry                         */
